name: Steve Azure Account Auth Test POC
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - features/**
permissions:
  id-token: write
  contents: read
jobs:
  windows-latest:
    runs-on: windows-latest
    environment: SteveAzureSandbox
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: OIDC Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      
      - name: 'Get resource group'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $resourceGroup = Get-AzResourceGroup
            Write-Host "Resource Group: $resourceGroup"
          azPSVersion: "latest"
          